DROP DATABASE IF EXISTS board;
CREATE DATABASE IF NOT EXISTS board;
USE board;
CREATE TABLE IF NOT EXISTS board (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  user VARCHAR(255) NOT NULL,
  content VARCHAR(255) NULL,
  PRIMARY KEY (ID)
);
INSERT INTO board (user, content)
  VALUES ("public", "");
